[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  functions = "netlify/functions"
  command = "npm run dev"
  port = 8888

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/saveFeedback"
  status = 200
  force = true

# SPA fallback - redirect all unmatched routes to index.html (except for files that exist)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle 404 errors for actual missing files
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 200
