[build]
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "20"

# Single Page App fallback — serves index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Functions directory left blank because this project has no serverless functions
