[build]
  # No build command required for this repo: index.html is at the repository root
  publish = "."
  functions = "netlify/functions"

[context.production]
  command = ""   # no build step

[context.deploy-preview]
  command = ""   # no build step
