name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy site to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Install netlify-cli
        run: npm install -g netlify-cli@latest

      - name: Build (no-op for static site)
        run: echo "No build step; deploying static files and functions"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          set -euo pipefail
          # Publish directory and functions as configured in netlify.toml
          netlify deploy --prod --dir=. --site="$NETLIFY_SITE_ID"
